name: Main Build

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package --file jakartaee-cafe/pom.xml

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy WAR
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az webapp deploy --resource-group jakartaee-cafe-group-reza --name jakartaee-cafe-web-reza --type war --src-path $GITHUB_WORKSPACE/jakartaee-cafe/target/jakartaee-cafe.war
