# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - cephalin-jboss5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E8F47942D426478A9EFA3A9F42B872B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DC7BA765942C43FD925ADDE4E270022C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4426E09FD654F2F810598FCD87E59FA }}

      - name: Deploy startup script
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --src-path '${{ github.workspace }}/src/main/jboss/config/createPasswordlessDataSource.sh' --name cephalin-jboss5 --resource-group cephalin-jboss5_group  --async true --type startup

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cephalin-jboss5'
          slot-name: 'Production'
          package: '*.war'
          
